2020-05-07 13:54:21,100 ERROR: Exception on /login [GET] [in d:\flaskproject\blog2\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\flaskproject\blog2\blog\routes.py", line 68, in login
    return render_template('login.html',  title='Sign In', form=form)
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "d:\flaskproject\blog2\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "d:\flaskproject\blog2\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\flaskproject\blog2\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\flaskproject\blog2\blog\templates\login.html", line 1, in top-level template code
    {% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %} {% block app_content %}
  File "D:\flaskproject\blog2\blog\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %} {% block title %} {% if title %}{{ title }} - Worchblog{% else %}Welcome to Worchblog{% endif %} {% endblock %} {% block navbar %}
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "D:\flaskproject\blog2\blog\templates\base.html", line 33, in block "content"
    {% endfor %} {% endif %} {% endwith %} {# application content needs to be provided in the app_content block #} {% block app_content %}{% endblock %}
  File "D:\flaskproject\blog2\blog\templates\login.html", line 12, in block "app_content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "d:\flaskproject\blog2\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2020-05-07 13:58:16,556 INFO: Wotchblog startup [in D:\flaskproject\blog2\blog\__init__.py:47]
2020-05-07 13:58:23,940 ERROR: Exception on /login [GET] [in d:\flaskproject\blog2\venv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\flaskproject\blog2\blog\routes.py", line 68, in login
    return render_template('login.html',  title='Sign In', form=form)
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "d:\flaskproject\blog2\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "d:\flaskproject\blog2\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\flaskproject\blog2\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\flaskproject\blog2\blog\templates\login.html", line 1, in top-level template code
    {% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %} {% block app_content %}
  File "D:\flaskproject\blog2\blog\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %} {% block title %} {% if title %}{{ title }} - Worchblog{% else %}Welcome to Worchblog{% endif %} {% endblock %} {% block navbar %}
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "D:\flaskproject\blog2\blog\templates\base.html", line 33, in block "content"
    {% endfor %} {% endif %} {% endwith %} {# application content needs to be provided in the app_content block #} {% block app_content %}{% endblock %}
  File "D:\flaskproject\blog2\blog\templates\login.html", line 12, in block "app_content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\flaskproject\blog2\venv\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "d:\flaskproject\blog2\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2020-05-07 14:39:59,727 INFO: Wotchblog startup [in D:\flaskproject\blog2\blog\__init__.py:47]
